### ISSUE TITLE
list file

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [geraudi/slim-skeleton#1]
http://localhost:8080/

only lists the .php files

normal this?

**Comment by devanishidk** [comment]
I have same issue

**Comment by nikkii94** [comment]
Can you solved this?

**Comment by geraudi** [comment]
You have to configure a vhost. 
Example:
`<VirtualHost *:80>
    DocumentRoot "/var/www/projet/public"
    ServerName your-domain.tld
    <Directory "/var/www/project/public">
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
    </Directory>
</VirtualHost>`

Restart Apache and go to: your-domain.tld
